[package]
name = "benchmarks"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "client-binary"
path = "src/client-binary.rs"


[dependencies]
tokio = { version = "1.17.0", features = ["full"] }
reqwest = "0.11.10"
